[package]
name = "lores-websites"
version = "0.1.4"
edition = "2021"

[dependencies]
lores-websites-node = { path = "../lores-websites-node" }
axum = { version = "0.8", features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
futures-util = "0.3"
lazy_static = "1"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs"] }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum", "vendored"] }
hex = "0.4"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
